# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    tags:
    - v*
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: valentinrudloff/generate-dumb-things-deb:latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          cd ..
          mv DumbThingsToRemember/* /build
          cd /build
          ./build_deb/build_deb.sh
      - uses: actions/upload-artifact@v2
        with:
          name: debian-pck
          path: /build/*.deb
          retention-days: 1
  verify:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: valentinrudloff/generate-dumb-things-deb:latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: debian-pck
      - name: build
        run: |
          cd ..
          mv DumbThingsToRemember/* /build
          cd /build
          ./build_deb/verify_deb.sh
