# This is a basic workflow to help you get started with Actions

name: Build & Verify DEB

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
    - v*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: valentinrudloff/generate-dumb-things-deb:latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          cd ..
          mv DumbThingsToRemember/* /build
          cd /build
          ./build_deb/build_deb.sh ${{ github.event.release.tag_name }}
      - uses: actions/upload-artifact@v2
        with:
          name: debian-pck-${{ github.event.release.tag_name }}
          path: /build/build_deb/*.deb
          retention-days: 1 # Should be revised 
  verify:
    # The type of runner that the job will run on
    needs: build
    runs-on: ubuntu-latest
    container:
      image: valentinrudloff/generate-dumb-things-deb:latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: debian-pck
      - name: build
        run: |
          cd ..
          mv DumbThingsToRemember/* /build
          cd /build
          mv *.deb /build/build_deb
          ./build_deb/verify_deb.sh ${{ github.event.release.tag_name }}
