# This is a basic workflow to help you get started with Actions

name: Update Blog

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
      - 'README.md' # run this workflow only on changes to README.md
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Checkout Blog
        uses: actions/checkout@master
        with: 
          repository: gamma-software/gamma-software.github.io
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ./blog
      - name: Install pandoc to concatenate markdowns
        run: >
          sudo apt install pandoc
      - name: Concatenate the template and the dumb things 
        run: >
          pandoc -s .github/template-blog.md README.md -o ./blog/_projects/2021-12-25-dumb-things-to-remember.md
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN }}
        with:
          source-directory: './blog/_projects'
          target-directory: '_projects'
          destination-github-username: 'gamma-software'
          destination-repository-name: 'gamma-software.github.io'
          user-email: valentin.rudloff.perso@gmail.com
          target-branch: main
          commit-message: Update blog from $GITHUB_REF
      - name: Go check the modification
        run: echo -e "https://github.com/Gamma-Software/gamma-software.github.io or https://gamma-software.github.io/"
